### ISSUE TITLE
How to SendTextMessage to a Group?

### ISSUE THREAD

**Issue by V-inz** [o3ma/o3#12]
What's the recipient string, if you SendTextMessage() to a group.
Can't find anything in docs and all I tried failed.

Sample: In the **o3demo**, if you'd like to answer incoming GroupTextMessage:
```
   ...
   // main rx loop
   for receivedMessage := range receiveMsgChan {
      switch msg := receivedMessage.Msg.(type) {
         case o3.GroupTextMessage:
            fmt.Printf("GroupTextMessage: ~%s [%s] for Group [%x] created by [%s]\n", msg.PubNick(), msg.Sender(), msg.GroupID(), msg.GroupCreator())
            fmt.Printf("GroupTextMessage: Recipient: [%s], that's me!\n", msg.Recipient())
            fmt.Printf("GroupTextMessage: Text: %s\n", msg.Text())

            err = ctx.SendTextMessage(<WHAT_TO_USE_HERE>, "Exactly!", sendMsgChan)
            // msg.Sender() will send a private message
            // msg.Recipient() will start a private conversation to self, hopefully not auto-answered to self (o3demo)!
      }
   }
```

**Comment by willnix** [comment]
You stumbled right upon a missing feature. That's why you couldn't find a way to do it...
Sorry about that!
I am working on it right now and it should be pretty straight forward, so expect a commit within the hour.

**Comment by willnix** [comment]
https://en.oxforddictionaries.com/definition/within_the_hour
 :-P

**Comment by willnix** [comment]
Well I have trouble testing my code right now, probably because the servers blocked me again...
Nevertheless I have pushed some changes to "testing" branches in o3 and o3demo.
It would be very helpful if you could try it out.
Please note that so far there is only support for GroupTextMessages.

**Comment by willnix** [comment]
I managed to test it and it does not work yet. :/
You might have to wait until tomorrow...

**Comment by V-inz** [comment]
thats ok, I'll create some pull request on the demo

**Comment by willnix** [comment]
So you got it working?

**Comment by willnix** [comment]
So the handling of groups is still very ugly but sending group text messages works now.

**Comment by V-inz** [comment]
btw. think, we have to store all group-info to a file. Things get messy, if you missed one of the management-messages because client was restarted.
All incoming GroupMessages have to create (and save?) group-info we are missing, also if other info (members, name, ...) is still missing. Even incoming GroupTextMessage, if the Sender is still missing in the list. Maybe this needs a layer above your raw communication.
Will try your newest commit tonight.

**Comment by willnix** [comment]
What you say about group management is all true except this:
> Even incoming GroupTextMessage, if the Sender is still missing in the list. Maybe this needs a layer above your raw communication.
This would enable anyone knowing a group ID to enter the group without the group admins approval.

**Comment by V-inz** [comment]
ok, you're right. So storing the incoming group-management or current state of the groups is essential.

**Comment by V-inz** [comment]
nice
can confirm, group-chat is working. currently, as expected, you should not forget to resync groups

**Comment by V-inz** [comment]
currently you use different names for "LoadFromFile":
```
err = groups.LoadFromFile(grppath)
err = ctx.ID.Contacts.ImportFrom(abpath)
```

also will be hard to translate to `ctx.ID.Groups[Sender][GroupID]` from `GroupDirectory`

**Comment by willnix** [comment]
You're right the names should be consistent.

About the ctx.ID.Groups thing. That was a hack so we could test whether sending group messages works at all. It will be replaced by the GroupDirectory. But maybe  I'll do as you propose and implement GroupDirectory.groups as a map.

**Comment by V-inz** [comment]
would be nice if you could use it the same way, as in Contacts: `ctx.ID.*Groups*.ImportFrom(grppath)`-
So there should not be a new structure for storing groups, think you already have one: `ctx.ID.Groups[Sender][GroupID]`

**Comment by willnix** [comment]
Check out the new commit: dce3b5ee165999574ae39172829c18850feb1ab1
I did something similar...

**Comment by V-inz** [comment]
thats working fine!
maybe you could look at my testing-repos for some extension
https://github.com/V-inz/o3demo/blob/testing/main.go
