### ISSUE TITLE
unknown MessageType: 80

### ISSUE THREAD

**Issue by V-inz** [o3ma/o3#17]
in file `packethandler.go` function `handleMessagePacket` [line 188](https://github.com/o3ma/o3/blob/master/packethandler.go#L188) I got

"o3: unknown MessageType: 80"

Decimal 80 is 0x50. I got if while my client was added to a group, after the normal messages (GroupManageSetMembersMessage, GroupManageSetNameMessage, GroupManageSetMembersMessage).

Is it the Group-Image?

**Comment by simmac** [comment]
> Is it the Group-Image?

Looks like it, at least that's how @blizzard4591[ interprets the message in his openMittsu project](https://github.com/blizzard4591/openMittsu/blob/ae6364826a0b918a51c20c2e1caa6d0457f8e964/src/protocol/ProtocolSpecs.h#L57).

**Comment by willnix** [comment]
It is!
