### ISSUE TITLE
Java called

### ISSUE THREAD

**Issue by keks** [o3ma/o3#9]
They want their identifiers back:
```
func NewGroupManageSetMembersMessages(sc *SessionContext, group Group) []GroupManageSetMembersMessage
func NewGroupManageSetNameMessages(sc *SessionContext, group Group) []GroupManageSetNameMessage
func NewGroupMemberLeftMessages(sc *SessionContext, group Group) []GroupMemberLeftMessage
```

;)

**Comment by cryptix** [comment]
Trolling asside, how would you manage these prefixes? (sub)packges? 

For something even bigger with more common prefixes (like [aws](https://godoc.org/github.com/aws/aws-sdk-go/service/applicationdiscoveryservice) or goog' appengine) this might work out but AFAICT(*) it's only the `Group..Message` stuff that pops up here. I'm not sure splitting up that will result in something meaningfull witth with the current size of the api surface and personally I find `FullDescriptiveCamalCasesNames` much more readable than nifty abbreviations.


(*): `go doc github.com/o3ma/o3` gives a nice, uncluttered overview of the identifiiers.
